[project]
name = "orders-view"
version = "0.1.0"
description = "High-Performance Canvas Booking Interval Explorer"
readme = "README.md"
authors = [
    { name = "Simon Labzoff", email = "semyon@example.com" }
]
requires-python = ">=3.12"
dependencies = []

[tool.uv]
package = false

[project.scripts]
orders-view = "orders_view:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
